// This file is automatically generated. Do not edit.
localparam SPD_ANALOG_CHANNELS     = 4 ;
localparam SPD_PARALLEL_SAMPLES    = 4 ;
localparam SPD_INTERLEAVED         = 0 ;
localparam SPD_DATAWIDTH_BITS      = 16 ;
localparam SPD_PROCESSING_CHANNELS_FULL       = 4 ;
localparam SPD_PROCESSING_CHANNELS            = 4 ;
localparam SPD_VIRTUAL_CHANNELS    = 0 ;
localparam DONT_CARE = 0;
localparam CH_A = 0;
localparam CH_B = 1;
localparam CH_C = 2;
localparam CH_D = 3;
