`define UL1_DATA_BUS_WIDTH 440
`define UL1_SPD_ANALOG_CHANNELS 4
`define UL1_SPD_DATAWIDTH_BITS 16
`define UL1_SPD_PARALLEL_SAMPLES 4
`define UL1_SPD_NUM_AUX_TRIG_BITS 5
`define UL1_SPD_NUM_CH_TRIG_BITS 5
`define UL1_SPD_NUM_TRIG_ADDBITS 2
`define UL1_SPD_TIMESTAMP_WIDTH_BITS 64
